/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MY: typeof import('./src/components/MY.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
    TodoDialog: typeof import('./src/components/TodoDialog.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoItems: typeof import('./src/components/TodoItems.vue')['default']
    VListContent: typeof import('vuetify/lib')['VListContent']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
  }
}
